sudo: required

services:
  - docker

before_install:
  - set -e

env:
  - GITLAB_VERSION=10.5.6
  - GITLAB_VERSION=10.6.6
  - GITLAB_VERSION=10.8.7
  - GITLAB_VERSION=11.4.0

script:
  - image_name="inovex/gitlab:${GITLAB_VERSION?}-${TRAVIS_COMMIT:0:7}"
  - docker login -u "${DOCKER_USERNAME?}" -p "${DOCKER_PASSWORD?}"
  - docker build --pull --build-arg "GITLAB_VERSION=${GITLAB_VERSION?}" --tag ${image_name?} .
  - docker tag ${image_name?} ${image_name?}-dev
  - docker push ${image_name?}-dev
  - |
    if [[ "${TRAVIS_BRANCH?}" == "master" && "${TRAVIS_PULL_REQUEST?}" == "false" ]]; then
      docker push ${image_name?}
    fi
