sudo: required

services:
  - docker

before_install:
  - set -e

env:
  - GITLAB_VERSION=10.5.6 # latest 10.5.x
  - GITLAB_VERSION=10.6.0 # latest 10.6.x
  - GITLAB_VERSION=10.8.7
  - GITLAB_VERSION=11.3.0


script:
  - image_name="inovex/gitlab:${GITLAB_VERSION?}-${TRAVIS_COMMIT:0:7}"
  - docker build --pull --build-arg "GITLAB_VERSION=${GITLAB_VERSION?}" --tag ${image_name?} .
  - if [[ "${TRAVIS_BRANCH?}" == "master" && "${TRAVIS_PULL_REQUEST?}" == "false" ]]; then
    docker login -u "${DOCKER_USERNAME?}" -p "${DOCKER_PASSWORD?}";
    docker push ${image_name?};
    fi
